# %%

import pandas as pd
import numpy as np
from os.path import join

pd.set_option('display.max_columns', None)
basepath = "surveys"

# %% 2015
# first row identifies multiselect questions
# second row - column headers are the questions
# categories included in each header

fin = join(basepath, "2015 Stack Overflow Developer Survey Responses.csv")
df15 = pd.read_csv(fin, engine="python", skiprows=1)

for col in df15.columns:
    print(col)

# %% 2015

columns = [
    'country',
    'age',
    'gender',
    'tabs_spaces',
    'years_experience',
    'occupation',
    'os',
    'os_other',
    'tech_Android',
    'tech_Arduino/RaspberryPi',
    'tech_AngularJS',
    'tech_C',
    'tech_C++',
    'tech_C++11',
    'tech_C#',
    'tech_Cassandra',
    'tech_CoffeeScript',
    'tech_Cordova',
    'tech_Clojure',
    'tech_Cloud',
    'tech_Dart',
    'tech_F#',
    'tech_Go',
    'tech_Hadoop',
    'tech_Haskell',
    'tech_iOS',
    'tech_Java',
    'tech_JavaScript',
    'tech_LAMP',
    'tech_Matlab',
    'tech_MongoDB',
    'tech_Node.js',
    'tech_Objective-C',
    'tech_Perl',
    'tech_PHP',
    'tech_Python',
    'tech_R',
    'tech_Redis',
    'tech_Ruby',
    'tech_Rust',
    'tech_Salesforce',
    'tech_Scala',
    'tech_Sharepoint',
    'tech_Spark',
    'tech_SQL',
    'tech_SQL Server',
    'tech_Swift',
    'tech_VisualBasic',
    'tech_WindowsPhone',
    'tech_Wordpress',
    'tech_Other',
    'interest_Android',
    'interest_Arduino/RaspberryPi',
    'interest_AngularJS',
    'interest_C',
    'interest_C++',
    'interest_C++11',
    'interest_C#',
    'interest_Cassandra',
    'interest_CoffeeScript',
    'interest_Cordova',
    'interest_Clojure',
    'interest_Cloud',
    'interest_Dart',
    'interest_F#',
    'interest_Go',
    'interest_Hadoop',
    'interest_Haskell',
    'interest_iOS',
    'interest_Java',
    'interest_JavaScript',
    'interest_LAMP',
    'interest_Matlab',
    'interest_MongoDB',
    'interest_Node.js',
    'interest_Objective-C',
    'interest_Perl',
    'interest_PHP',
    'interest_Python',
    'interest_R',
    'interest_Redis',
    'interest_Ruby',
    'interest_Rust',
    'interest_Salesforce',
    'interest_Scala',
    'interest_Sharepoint',
    'interest_Spark',
    'interest_SQL',
    'interest_SQL Server',
    'interest_Swift',
    'interest_VisualBasic',
    'interest_WindowsPhone',
    'interest_Wordpress',
    'interest_Other',
    'edu_NoFormal',
    'edu_OnTheJob',
    'edu_Bootcamp',
    'edu_Online',
    'edu_Mentorship',
    'edu_IndustryCert',
    'edu_SomeCollege',
    'edu_BSinCS',
    'edu_MastersinCS',
    'edu_PhDinCS',
    'edu_Other',
    'salary',
    'salary_midpoint',
    'employment',
    'industry',
    'satisfaction',
    'purchaser',
    'remote',
    'job_12months',
    'job_looking',
    'job_op_Salary',
    'job_op_Equity',
    'job_op_Decisions',
    'job_op_Insurance',
    'job_op_Industry',
    'job_op_TechStack',
    'job_op_Size',
    'job_op_Stage',
    'job_op_WorkLifeBalance',
    'job_op_Advancement',
    'job_op_Title',
    'job_op_Location',
    'job_op_Colleagues',
    'job_op_Culture',
    'job_op_Reputation',
    'job_op_TaskImportance',
    'job_op_Remote',
    'job_op_Flexible',
    'job_remote_op',
    'job_search_annoy_Time',
    'job_search_annoy_Qualified',
    'job_search_annoy_Tnteresting',
    'job_search_annoy_RarelyRespond',
    'job_search_annoy_CV',
    'job_search_annoy_TimeForInterview',
    'job_search_annoy_Interview',
    'job_recruiter_contact',
    'perception_recruiter',
    'perception_Email',
    'perception_LinkedIn',
    'perception_Xing',
    'perception_Phone',
    'perception_SOcareers',
    'perception_Twitter',
    'perception_Facebook',
    'email_personalized',
    'email_projects',
    'email_activity',
    'email_team',
    'email_culture',
    'email_salary',
    'email_benefits',
    'email_SOlink',
    'urgent_Salary',
    'urgent_Benefits',
    'urgent_Company',
    'urgent_TechStack',
    'urgent_Location',
    'urgent_Title',
    'urgent_Colleagues',
    'urgent_ProductDetails',
    'contact_Headhunter',
    'contact_InHouseRecruiter',
    'contact_InHouseTech',
    'contact_Manager',
    'contact_Developer',
    'interview_improvement_MoreLiveCode',
    'interview_improvement_FlexibleSchedule',
    'interview_improvement_RemoteTnterviews',
    'interview_improvement_IntroduceBoss',
    'interview_improvement_IntroduceTeam',
    'interview_improvement_Coffee',
    'interview_improvement_Workplace',
    'interview_improvement_FewerBrainteasers',
    'interview_improvement_BetterPreparation',
    'so_careers_NoSpam',
    'so_careers_ForProgrammers',
    'so_careers_RevelantJobs',
    'so_careers_ShowcaseActivity',
    'so_careers_Jobs',
    'so_careers_Other',
    'caffinated_per_day',
    'hobby_programming_hours',
    'so_frequency',
    'text_editor',
    'text_editor_other',
    'color_theme',
    'source_control_Git',
    'source_control_Mercurial',
    'source_control_SVN',
    'source_control_CVS',
    'source_control_Perforce',
    'source_control_TFS',
    'source_control_DCVS',
    'source_control_Bitkeeper',
    'source_control_Legacy',
    'source_control_None',
    'source_control_Other',
    'prefered_source_control',
    'prefered_source_control_other',
    'so_use_forjob',
    'so_use_tohelp',
    'so_use_vital',
    'so_use_presence',
    'so_use_demonstrate',
    'so_use_communication',
    'so_use_personal',
    'so_use_tolearn',
    'so_use_none',
    'so_find_period',
    'why_use_HelpOthers',
    'why_use_HelpFuture',
    'why_use_demonstrate',
    'why_use_selfpromotion',
    'why_use_senseofresponsibility',
    'why_use_noidea',
    'why_use_dontwantto',
    'why_use_wantto',
]

df15 = pd.read_csv(
    fin,
    engine="python",
    skiprows=2,
    header=None,
    names=columns
)

# %%

col_cat = [
    'tech_Android',
    'tech_Arduino',
    'tech_AngularJS',
    'tech_C',
    'tech_C++',
    'tech_C++11',
    'tech_C#',
    'tech_Cassandra',
    'tech_CoffeeScript',
    'tech_Cordova',
    'tech_Clojure',
    'tech_Cloud',
    'tech_Dart',
    'tech_F#',
    'tech_Go',
    'tech_Hadoop',
    'tech_Haskell',
    'tech_iOS',
    'tech_Java',
    'tech_JavaScript',
    'tech_LAMP',
    'tech_Matlab',
    'tech_MongoDB',
    'tech_Node.js',
    'tech_ObjectiveC',
    'tech_Perl',
    'tech_PHP',
    'tech_Python',
    'tech_R',
    'tech_Redis',
    'tech_Ruby',
    'tech_Rust',
    'tech_Salesforce',
    'tech_Scala',
    'tech_Sharepoint',
    'tech_Spark',
    'tech_SQL',
    'tech_SQL Server',
    'tech_Swift',
    'tech_VisualBasic',
    'tech_WindowsPhone',
    'tech_Wordpress',
    'tech_Other',
    'interest_Android',
    'interest_Arduino',
    'interest_AngularJS',
    'interest_C',
    'interest_C++',
    'interest_C++11',
    'interest_C#',
    'interest_Cassandra',
    'interest_CoffeeScript',
    'interest_Cordova',
    'interest_Clojure',
    'interest_Cloud',
    'interest_Dart',
    'interest_F#',
    'interest_Go',
    'interest_Hadoop',
    'interest_Haskell',
    'interest_iOS',
    'interest_Java',
    'interest_JavaScript',
    'interest_LAMP',
    'interest_Matlab',
    'interest_MongoDB',
    'interest_Node.js',
    'interest_ObjectiveC',
    'interest_Perl',
    'interest_PHP',
    'interest_Python',
    'interest_R',
    'interest_Redis',
    'interest_Ruby',
    'interest_Rust',
    'interest_Salesforce',
    'interest_Scala',
    'interest_Sharepoint',
    'interest_Spark',
    'interest_SQL',
    'interest_SQL Server',
    'interest_Swift',
    'interest_VisualBasic',
    'interest_WindowsPhone',
    'interest_Wordpress',
    'interest_Other',
    'edu_NoFormal',
    'edu_OnTheJob',
    'edu_Bootcamp',
    'edu_Online',
    'edu_Mentorship',
    'edu_IndustryCert',
    'edu_SomeCollege',
    'edu_BSinCS',
    'edu_MastersinCS',
    'edu_PhDinCS',
    'edu_Other',
    'job_op_Salary',
    'job_op_Equity',
    'job_op_Decisions',
    'job_op_Insurance',
    'job_op_Industry',
    'job_op_TechStack',
    'job_op_Size',
    'job_op_Stage',
    'job_op_WorkLifeBalance',
    'job_op_Advancement',
    'job_op_Title',
    'job_op_Location',
    'job_op_Colleagues',
    'job_op_Culture',
    'job_op_Reputation',
    'job_op_TaskImportance',
    'job_op_Remote',
    'job_op_Flexible',
    'job_search_annoy_Time',
    'job_search_annoy_Qualified',
    'job_search_annoy_Tnteresting',
    'job_search_annoy_RarelyRespond',
    'job_search_annoy_CV',
    'job_search_annoy_TimeForInterview',
    'job_search_annoy_Interview',
    'urgent_Salary',
    'urgent_Benefits',
    'urgent_Company',
    'urgent_TechStack',
    'urgent_Location',
    'urgent_Title',
    'urgent_Colleagues',
    'urgent_ProductDetails',
    'contact_Headhunter',
    'contact_InHouseRecruiter',
    'contact_InHouseTech',
    'contact_Manager',
    'contact_Developer',
    'interview_improvement_MoreLiveCode',
    'interview_improvement_FlexibleSchedule',
    'interview_improvement_RemoteTnterviews',
    'interview_improvement_IntroduceBoss',
    'interview_improvement_IntroduceTeam',
    'interview_improvement_Coffee',
    'interview_improvement_Workplace',
    'interview_improvement_FewerBrainteasers',
    'interview_improvement_BetterPreparation',
    'so_careers_NoSpam',
    'so_careers_ForProgrammers',
    'so_careers_RevelantJobs',
    'so_careers_ShowcaseActivity',
    'so_careers_Jobs',
    'so_careers_Other',
    'source_control_Git',
    'source_control_Mercurial',
    'source_control_SVN',
    'source_control_CVS',
    'source_control_Perforce',
    'source_control_TFS',
    'source_control_DCVS',
    'source_control_Bitkeeper',
    'source_control_Legacy',
    'source_control_None',
    'source_control_Other',
    'so_use_forjob',
    'so_use_tohelp',
    'so_use_vital',
    'so_use_presence',
    'so_use_demonstrate',
    'so_use_communication',
    'so_use_personal',
    'so_use_tolearn',
    'so_use_none',
    'why_use_HelpOthers',
    'why_use_HelpFuture',
    'why_use_demonstrate',
    'why_use_selfpromotion',
    'why_use_senseofresponsibility',
    'why_use_noidea',
    'why_use_dontwantto',
    'why_use_wantto',
]

df15[col_cat] = df15[col_cat].fillna(0)
df15[col_cat] = df15[col_cat].ne(0).mul(1)

df15

# %%

cols = [
    'salary',
    'age',
    'years_experience',
    'industry',
    'occupation',
    'satisfaction'
]

for col in cols:
    print(f"'{col}': {pd.unique(df15[col])},")

# %%

col_map = {
    'salary' : {
        'Rather not say' : np.nan,
        'Unemployed' : 0,
        'Less than $20,000' : 10000,
        '$20,000 - $40,000' : 30000,
        '$40,000 - $60,000' : 50000,
        '$60,000 - $80,000' : 70000,
        '$80,000 - $100,000' : 90000,
        '$100,000 - $120,000' : 110000,
        '$120,000 - $140,000' : 130000,
        '$140,000 - $160,000' : 150000,
        'More than $160,000' : 170000,
    },
    'age': {
        'Prefer not to disclose' : np.nan,
        '< 20' : 18,
        '20-24' : 22,
        '25-29' : 27,
        '30-34' : 32,
        '35-39' : 37,
        '40-50' : 45,
        '51-60' : 55,
        '> 60' : 65,
    },
    'years_experience': {
        'Less than 1 year' : 1,
        '1 - 2 years' : 2,
        '2 - 5 years' : 5,
        '6 - 10 years' : 7,
        '11+ years' : 11,
    },
    'industry': {
        'Finance / Banking' : 'Financing',
        'Consumer Products' : 'Consumer',
        'Foundation / Non-Profit' : 'NonProfit',
        'Media / Advertising' : 'Media',
        'Other (please specify)' : 'Other',
        "I'm a student" : 'Student',
        'Software Products' : 'Software',
        'Not Currently Employed' : 'NotEmployed',
        'Web Services' : 'Web',
        # 'Aerospace',
        # 'Consulting',
        # 'Defense',
        # 'Education'
        # 'Gaming',
        # 'Government'
        # 'Healthcare',
        # 'Internet',
        # 'Manufacturing'
        # 'Retail',
        # 'Telecommunications',
    },
    'occupation': {
        'Back-end web developer' : "Web",
        'Business intelligence or data warehousing expert' : "DataWarehouse",
        'Data scientist' : "DataScientist",
        'Database administrator' : 'Database',
        'Desktop developer': 'Desktop',
        'Developer with a statistics or mathematics background' : 'Stats',
        'Embedded application developer' : 'Embedded',
        'Enterprise level services developer' : 'Enterprise',
        'Executive (VP of Eng., CTO, CIO, etc.)' : 'Executive',
        'Front-end web developer' : 'Web',
        'Full-stack web developer' : 'Web',
        'Graphics programmer' : 'Graphics',
        'Growth hacker' : 'GrowthHacker',
        'Machine learning developer' : 'ML',
        'Mobile developer' : 'Mobile',
        'Mobile developer - Android' : 'Mobile',
        'Mobile developer - iOS' : 'Mobile',
        'Mobile developer - Windows Phone' : 'Mobile',
        'Product manager' : 'ProductManager',
        'Quality Assurance' : 'Quality',
        'System administrator' : 'System',
        # 'DevOps',
        # 'Student',
        # 'Designer',
    },
    'satisfaction': {
        'Other (please specify)' : 0,
        'I hate my job' : 1,
        "I'm somewhat dissatisfied with my job" : 2,
        "I'm neither satisfied nor dissatisfied with my job" : 3,
        "I'm somewhat satisfied with my job" : 4,
        'I love my job' : 5
    }
}
