import numpy as np

value_map = {
    "salary": {
        "$10,000 - $20,000" : 150000,
        "$100,000 - $110,000" : 105000,
        "$100,000 - $120,000" : 110000,
        "$110,000 - $120,000" : 115000,
        "$120,000 - $130,000" : 125000,
        "$120,000 - $140,000" : 130000,
        "$130,000 - $140,000" : 135000,
        "$140,000 - $150,000" : 145000,
        "$140,000 - $160,000" : 150000,
        "$150,000 - $160,000" : 155000,
        "$160,000 - $170,000" : 165000,
        "$170,000 - $180,000" : 175000,
        "$180,000 - $190,000" : 185000,
        "$190,000 - $200,000" : 195000,
        "$20,000 - $30,000" : 25000,
        "$20,000 - $40,000" : 30000,
        "$30,000 - $40,000" : 35000,
        "$40,000 - $50,000" : 45000,
        "$40,000 - $60,000" : 50000,
        "$50,000 - $60,000" : 55000,
        "$60,000 - $70,000" : 65000,
        "$60,000 - $80,000" : 70000,
        "$70,000 - $80,000" : 75000,
        "$80,000 - $100,000" : 0000 ,
        "$80,000 - $90,000" : 85000,
        "$90,000 - $100,000" : 95000,
        "<$20,000" : 10000,
        ">$140,000" : 150000,
        "Less than $10,000" : 000 ,
        "Less than $20,000" : 10000,
        "More than $160,000" : 180000,
        "More than $200,000" : 220000,
        "Other (please specify)" : np.nan,
        "Rather not say" : np.nan,
        "Student / Unemployed" : np.nan,
        "Unemployed" : np.nan,
    },
    "satisfaction": {
        "Extremely dissatisfied" : 0,
        "Extremely satisfied" : 4,
        "FML" : 0,
        "Hate my job" : 0,
        "I don't have a job" : np.nan,
        "I enjoy going to work" : 3,
        "I hate my job" : 0,
        "I love my job" : 4,
        "I wish I had a job!" : np.nan,
        "I'm neither satisfied nor dissatisfied" : 2,
        "I'm neither satisfied nor dissatisfied with my job" : 2,
        "I'm not happy in my job" : 1,
        "I'm somewhat dissatisfied with my job" : 1,
        "I'm somewhat satisfied with my job" : 3,
        "It pays the bills" : 2,
        "It's a paycheck" : 2,
        "Its a paycheck" : 2,
        "Love my job" : 4,
        "Moderately dissatisfied" : 1,
        "Moderately satisfied" : 3,
        "Neither satisfied nor dissatisfied" : 2,
        "Other (please specify)" : np.nan,
        "Slightly dissatisfied" : 1,
        "Slightly satisfied" : 3,
        "So happy it hurts" : 4,
        "Very dissatisfied" : 1,
        "Very satisfied" : 4,
    },
    "age": {
        "18 - 24 years old" : 21,
        "20-24" : 22,
        "25 - 34 years old" : 30,
        "25-29" : 27,
        "30-34" : 32,
        "35 - 44 years old" : 40,
        "35-39" : 37,
        "40-49" : 45,
        "40-50" : 45,
        "45 - 54 years old" : 50,
        "50-59" : 55,
        "51-60" : 56,
        "55 - 64 years old" : 60,
        "65 years or older" : 70,
        "< 20" : 18,
        "> 60" : 65,
        ">60" : 65,
        "Prefer not to disclose" : np.nan,
        "Under 18 years old" : 16,
    },
    "gender": {
        "Female" : "female",
        "Gender non-conforming" : "other",
        "Male" : "male",
        "Man" : "male",
        "Non-binary, genderqueer, or gender non-conforming" : "other",
        "Other" : "other",
        "Prefer not to disclose" : np.nan,
        "Transgender" : "other",
        "Woman" : "female",
    },
    "years_coding": {
        "0-2 years" : 1,
        "1" : 1,
        "1 - 2 years" : 2,
        "1 to 2 years" : 2,
        "10" : 10,
        "10 to 11 years" : 10,
        "11" : 11,
        "11 to 12 years" : 12,
        "11+ years" : 15,
        "12" : 12,
        "12 to 13 years" : 13,
        "12-14 years" : 13,
        "13" : 13,
        "13 to 14 years" : 14,
        "14" : 14,
        "14 to 15 years" : 15,
        "15" : 15,
        "15 to 16 years" : 16,
        "15-17 years" : 16,
        "16" : 16,
        "16 to 17 years" : 17,
        "17" : 17,
        "17 to 18 years" : 18,
        "18" : 18,
        "18 to 19 years" : 19,
        "18-20 years" : 20,
        "19" : 19,
        "19 to 20 years" : 20,
        "2" : 2,
        "2 - 5 years" : 3,
        "2 to 3 years" : 3,
        "2/5/2013" : 3,  # 2 - 5
        "2/5/2014" : 3,  # 2 - 5
        "20" : 20,
        "20 or more years" : 22,
        "21" : 21,
        "21-23 years" : 22,
        "22" : 22,
        "23" : 23,
        "24" : 24,
        "24-26 years" : 25,
        "25" : 25,
        "26" : 26,
        "27" : 27,
        "27-29 years" : 28,
        "28" : 28,
        "29" : 29,
        "3" : 3,
        "3 to 4 years" : 4,
        "3-5 years" : 4,
        "30" : 30,
        "30 or more years" : 32,
        "31" : 31,
        "32" : 32,
        "33" : 33,
        "34" : 34,
        "35" : 35,
        "36" : 36,
        "37" : 37,
        "38" : 38,
        "39" : 39,
        "4" : 4,
        "4 to 5 years" : 5,
        "40" : 4,
        "40944" : 3,  # 2 - 5
        "41" : 41,
        "41070" : 8,  # 6 - 10
        "41310" : 3,  # 2 - 5
        "41435" : 8,  # 6 - 10
        "42" : 42,
        "43" : 43,
        "44" : 44,
        "45" : 45,
        "46" : 46,
        "47" : 47,
        "48" : 48,
        "49" : 49,
        "5" : 5,
        "5 to 6 years" : 6,
        "50" : 50,
        "6" : 6,
        "6 - 10 years" : 8,
        "6 to 7 years" : 7,
        "6-8 years" : 7,
        "6/10/2013" : 8,  # 6 - 10
        "6/10/2014" : 8,  # 6 - 10
        "7" : 7,
        "7 to 8 years" : 8,
        "8" : 8,
        "8 to 9 years" : 9,
        "9" : 9,
        "9 to 10 years" : 10,
        "9-11 years" : 10,
        "<2" : 1,
        "Less than 1 year" : 0,
        "Less than a year" : 0,
        "More than 50 years" : 55,
    },
    "occu_nondev": {
        "Analyst or consultant" : "analyst",
        "C-suite executive" : "executive",
        "Data scientist" : "data_scientist",
        "Designer or illustrator" : "designer",
        "Educator or academic" : "academic",
        "Elected official" : "other",
        "Marketing or sales manager" : "manager",
        "Other" : "other",
        "Product manager" : "manager",
    },
    "occupation": {
        "Academic researcher" : "academic",
        "Analyst" : "analyst",
        "Back-End Web Developer" : "dev_web",
        "Back-end developer" : "dev_web",
        "Back-end web developer" : "dev_web",
        "Business intelligence or data warehousing expert" : "data_engineer",
        "C-suite executive (CEO, CTO, etc.)" : "executive",
        "Data or business analyst" : "analyst",
        "Data scientist" : "data_scientist",
        "Data scientist or machine learning specialist" : "data_scientist",
        "Database Administrator" : "database",
        "Database administrator" : "database",
        "Designer" : "designer",
        "Desktop Application Developer" : "dev_desktop",
        "Desktop Software Developer" : "dev_desktop",
        "Desktop applications developer" : "dev_desktop",
        "Desktop developer" : "dev_desktop",
        "Desktop or enterprise applications developer" : "dev_enterprise",
        "DevOps" : "dev_ops",
        "DevOps specialist" : "dev_ops",
        "Developer with a statistics or mathematics background" : "dev_stats",
        "Developer, QA or test" : "QA",
        "Developer, back-end" : "dev_web",
        "Developer, desktop or enterprise applications" : "dev_desktop",
        "Developer, embedded applications or devices" : "dev_embed",
        "Developer, front-end" : "dev_web",
        "Developer, full-stack" : "dev_web",
        "Developer, game or graphics" : "dev_graphics",
        "Developer, mobile" : "dev_mobile",
        "Educator" : "academic",
        "Educator or academic researcher" : "academic",
        "Embedded Application Developer" : "dev_embed",
        "Embedded application developer" : "dev_embed",
        "Embedded applications or devices developer" : "dev_embed",
        "Embedded applications/devices developer" : "dev_embed",
        "Engineer, data" : "data_engineer",
        "Engineer, site reliability" : "data_engineer",
        "Engineering manager" : "manager",
        "Enterprise Level Services" : "dev_enterprise",
        "Enterprise level services developer" : "dev_enterprise",
        "Executive (VP of Eng, CTO, CIO, etc.)" : "executive",
        "Executive (VP of Eng., CTO, CIO, etc.)" : "executive",
        "Front-End Web Developer" : "dev_web",
        "Front-end developer" : "dev_web",
        "Front-end web developer" : "dev_web",
        "Full-Stack Web Developer" : "dev_web",
        "Full-stack developer" : "dev_web",
        "Full-stack web developer" : "dev_web",
        "Game or graphics developer" : "dev_graphics",
        "Graphic designer" : "designer",
        "Graphics programmer" : "dev_graphics",
        "Graphics programming" : "dev_graphics",
        "Growth hacker" : "growth_hacker",
        "I don't work in tech" : "non-tech",
        "IT Manager" : "manager",
        "IT Staff / System Administrator" : "admin",
        "Kernel / Driver Developer" : "dev_server",
        "Machine learning developer" : "data_scientist",
        "Machine learning specialist" : "data_scientist",
        "Manager of Developers or Team Leader" : "manager",
        "Marketing or sales professional" : "sales",
        "Mobile Application Developer" : "dev_mobile",
        "Mobile developer" : "dev_mobile",
        "Mobile developer - Android" : "dev_mobile",
        "Mobile developer - Windows Phone" : "dev_mobile",
        "Mobile developer - iOS" : "dev_mobile",
        "Other" : "other",
        "Product manager" : "manager",
        "QA or test developer" : "QA",
        "Quality Assurance" : "QA",
        "Quality assurance engineer" : "QA",
        "Scientist" : "academic",
        "Senior executive/VP" : "executive",
        "Server Programmer" : "dev_server",
        "Student" : "student",
        "System administrator" : "admin",
        "Systems Analyst" : "analyst",
        "Systems administrator" : "admin",
        "Web Application Developer" : "dev_web",
        "Web developer" : "dev_web",
        "other" : "other",
    },
    "employment": {
        "Employed full-time" : "full-time",
        "Employed part-time" : "part-time",
        "Freelance / Contractor" : "independent",
        "I prefer not to say" : np.nan,
        "I'm a student" : "student",
        "Independent contractor, freelancer, or self-employed" : "independent",
        "Not employed, and not looking for work" : "unemployed",
        "Not employed, but looking for work" : "unemployed",
        "Other" : "other",
        "Other (please specify)" : "other",
        "Prefer not to disclose" : np.nan,
        "Retired" : "retired",
        "Self-employed" : "independent",
        "Student" : "student",
        "Unemployed" : "unemployed",
    },
    "industry": {
        "Advertising" : "advertising",
        "Aerospace" : "aerospace",
        "Automotive" : "automotive",
        "Consulting" : "consulting",
        "Consumer Products" : "consumer",
        "Defense" : "defence",
        "Education" : "education",
        "Finance / Banking" : "finance",
        "Foundation / Non-Profit" : "non-profit",
        "Gaming" : "gaming",
        "Government" : "public",
        "Government agency or public school/university" : "government",
        "Healthcare" : "healthcare",
        "I don't know" : np.nan,
        "I prefer not to answer" : np.nan,
        "I'm a student" : "student",
        "Internet" : "web",
        "Manufacturing" : "manufacturing",
        "Media / Advertising" : "media",
        "Non-profit/non-governmental organization or private school/university" : "non-profit",
        "Not Currently Employed" : "unemployed",
        "Other" : "other",
        "Other (please specify)" : "other",
        "Pre-series A startup" : "startup",
        "Privately-held limited company, not in startup mode" : "private",
        "Publicly-traded corporation" : "corporation",
        "Retail" : "retail",
        "Software Products" : "software",
        "Sole proprietorship or partnership, not in startup mode" : "independent",
        "Something else" : "other",
        "State-owned company" : "government",
        "Student" : "student",
        "Telecommunications" : "telecommunications",
        "Venture-funded startup" : "startup",
        "Web Services" : "web",
    },
    "org_size": {
        "1,000 to 4,999 employees" : 2500,
        "1,000-3,000" : 1500,
        "1,000-4,999 employees" : 3000,
        "1-4 employees" : 2,
        "1/25/2013" : 15,  # 1 - 25
        "10 to 19 employees" : 15,
        "10,000 or more employees" : 15000,
        "10,000+ employees" : 15000,
        "10-19 employees" : 15,
        "100 to 499 employees" : 300,
        "100-499 employees" : 300,
        "101-999" : 500,
        "2 to 9 employees" : 7,
        "2-9 employees" : 7,
        "20 to 99 employees" : 60,
        "20-99 employees" : 60,
        "26-100" : 60,
        "3001" : 5000,
        "5,000 to 9,999 employees" : 7000,
        "5,000-9,999 employees" : 7000,
        "5-9 employees" : 7,
        "500 to 999 employees" : 700,
        "500-999 employees" : 700,
        "Fewer than 10 employees" : 5,
        "Fortune 1000 (1,000+)" : 5000,
        "I am not part of a company" : 1,
        "I am not sure" : np.nan,
        "I don't know" : np.nan,
        "I prefer not to answer" : np.nan,
        "Just me - I am a freelancer, sole proprietor, etc." : 1,
        "Mature Small Business (25-100)" : 75,
        "Mid Sized (100-999)" : 500,
        "Other (not working, consultant, etc.)" : 1,
        "Other (please specify)" : np.nan,
        "Start Up (1-25)" : 15,
        "Student" : np.nan,
    },
    "job_seek": {
        "I am actively looking for a job" : "looking",
        "I am actively looking for a new job" : "looking",
        "I am not interested in new job opportunities" : "not_looking",
        "I am not interested in other job opportunities" : "not_looking",
        "I am open to new job opportunities" : "open",
        "I'm not actively looking, but I am open to new opportunities" : "open",
        "I’m not actively looking, but I am open to new opportunities" : "open",
        "No" : "not_looking",
        "Yes" : "looking",
    },
    "remote": {
        "A few days each month" : "occasional",
        "About half the time" : "part_time",
        "All or almost all the time (I'm full-time remote)" : "full_time",
        "Full-time Remote" : "full_time",
        "Full-time remote" : "full_time",
        "I rarely work remote" : "occasional",
        "I rarely work remotely" : "occasional",
        "It's complicated" : "occasional",
        "Less than half the time, but at least one day each week" : "part_time",
        "Less than once per month / Never" : "occasional",
        "More than half, but not all, the time" : "part_time",
        "Never" : "never",
        "Occasionally" : "occasional",
        "Part-time Remote" : "part_time",
        "Part-time remote" : "part_time",
    },
    "education": {
        "Associate degree" : "associate_degree",
        "Associate degree (A.A., A.S., etc.)" : "associate_degree",
        "B.A. in Computer Science (or related field)" : "bachelors",
        "B.S. in Computer Science (or related field)" : "bachelors",
        "Bachelor's degree" : "bachelors",
        "Bachelor’s degree (B.A., B.S., B.Eng., etc.)" : "bachelors",
        "Bachelor’s degree (BA, BS, B.Eng., etc.)" : "bachelors",
        "Doctoral degree" : "doctoral",
        'Full-time, intensive program (e.g. "boot-camp")' : "bootcamp",
        "I never completed any formal education" : "no_formal",
        "I prefer not to answer" : "other",
        "I'm self-taught" : "self_taught",
        "Industry certification program" : "industry_cert",
        "Master's degree" : "masters",
        "Masters Degree in Computer Science (or related field)" : "masters",
        "Master’s degree (M.A., M.S., M.Eng., MBA, etc.)" : "masters",
        "Master’s degree (MA, MS, M.Eng., MBA, etc.)" : "masters",
        "Mentorship program (e.g. Flatiron School, GDI, etc.)" : "mentor",
        "On-the-job training" : "on_the_job",
        "Online class (e.g. Coursera, Codecademy, Khan Academy, etc.)" : "online",
        "Other doctoral degree (Ph.D, Ed.D., etc.)" : "doctoral",
        "Other doctoral degree (Ph.D., Ed.D., etc.)" : "doctoral",
        "Part-time program (e.g. night school)" : "night_school",
        "PhD in Computer Science (or related field)" : "doctoral",
        "Primary/elementary school" : "elementary",
        "Professional degree" : "professional_degree",
        "Professional degree (JD, MD, etc.)" : "professional_degree",
        "Secondary school" : "secondary",
        "Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)" : "secondary",
        "Some college coursework in Computer Science (or related field)" : "college",
        "Some college/university study without earning a bachelor's degree" : "college",
        "Some college/university study without earning a degree" : "college",
    },
    "edu_other": {
        "Bootcamp" : "bootcamp",
        "Coding competition" : "competition",
        "Completed an industry certification program (e.g. MCPD)" : "industry_cert",
        "Contributed to open source software" : "open_source",
        "Hackathon" : "hackathon",
        "Industry certification" : "industry_cert",
        "On-the-job training" : "on_the_job",
        "Online course" : "online",
        "Open source contributions" : "open_source",
        "Part-time/evening course" : "night_school",
        "Participated in a full-time developer training program or bootcamp" : "bootcamp",
        "Participated in a hackathon" : "hackathon",
        "Participated in online coding competitions (e.g. HackerRank, CodeChef, TopCoder)" : "competition",
        "Received on-the-job training in software development" : "on_the_job",
        "Self-taught" : "self_taught",
        "Taken a part-time in-person course in programming or software development" : "night_school",
        "Taken an online course in programming or software development (e.g. a MOOC)" : "online",
        "Taught yourself a new language, framework, or tool without taking a formal course" : "self_taught",
    },
    "undergrad": {
        "A business discipline" : 'business',
        "A business discipline (ex. accounting, finance, marketing)" : 'business',
        "A business discipline (such as accounting, finance, marketing, etc.)" : 'business',
        "A health science" : 'health',
        "A health science (ex. nursing, pharmacy, radiology)" : 'health',
        "A health science (such as nursing, pharmacy, radiology, etc.)" : 'health',
        "A humanities discipline" : 'humanities',
        "A humanities discipline (ex. literature, history, philosophy)" : 'humanities',
        "A humanities discipline (such as literature, history, philosophy, etc.)" : 'humanities',
        "A natural science" : 'science',
        "A natural science (ex. biology, chemistry, physics)" : 'science',
        "A natural science (such as biology, chemistry, physics, etc.)" : 'science',
        "A non-computer-focused engineering discipline" : 'engineering',
        "A social science" : 'social_science',
        "A social science (ex. anthropology, psychology, political science)" : 'social_science',
        "A social science (such as anthropology, psychology, political science, etc.)" : 'social_science',
        "Another engineering discipline (ex. civil, electrical, mechanical)" : 'engineering',
        "Another engineering discipline (such as civil, electrical, mechanical, etc.)" : 'engineering',
        "Computer engineering or electrical/electronics engineering" : 'engineering',
        "Computer programming or Web development" : 'computer',
        "Computer science or software engineering" : 'computer',
        "Computer science, computer engineering, or software engineering" : 'computer',
        "Fine arts or performing arts" : 'arts',
        "Fine arts or performing arts (ex. graphic design, music, studio art)" : 'arts',
        "Fine arts or performing arts (such as graphic design, music, studio art, etc.)" : 'arts',
        "I never declared a major" : 'none',
        "Information systems, information technology, or system administration" : 'IT',
        "Information technology, networking, or system administration" : 'IT',
        "Management information systems" : 'IT',
        "Mathematics or statistics" : 'stats',
        "Psychology" : 'social_science',
        "Something else" : 'other',
        "Web development or web design" : 'arts',
    },
    "os": {
        "BSD" : 'unix',
        "BSD/Unix" : 'unix',
        "Debian" : 'unix',
        "Fedora" : 'unix',
        "Linux" : 'unix',
        "Linux-based" : 'unix',
        "Mac OS X" : 'macos',
        "MacOS" : 'macos',
        "Mint" : 'unix',
        "Other" : 'other',
        "Other Linux" : 'unix',
        "Ubuntu" : 'unix',
        "Windows" : 'windows',
        "Windows 10" : 'windows',
        "Windows 7" : 'windows',
        "Windows 8" : 'windows',
        "Windows Vista" : 'windows',
        "Windows XP" : 'windows',
    }
}
